export const keyToPathMap: Record<string, string> = {
  '1': '/overview',
  '2-1': '/fishboat/local',
  '2-2': '/fishboat/international',
  '3': '/ports',
  '4': '/crew',
  '5-1': '/account/local',
  '5-2': '/account/international',
  '6-1': '/category/industry',
  '6-2': '/category/fishSpecies',
  '6-3': '/category/fishingGround',
  '7-1': '/activity/departure',
  '7-2': '/activity/arrival',
  '7-3': '/activity/location',
  '8': '/logout',
};
