import type { DataType } from "@/types/regCert/reg/international";

export const sampleData: DataType[] = [
  {
    key: '1',
    boatSymbol: 'VN001',
    boatType: 'Tàu cá xa bờ',
    regisDate: '2021-06-15',
    regisOffice: 'Chi cục Thủy sản Hà Tĩnh',
    occupation: ['Khai thác xa bờ', 'Đánh bắt mực'],
    harbourCode: 'HT001',
    inspectDate: '2023-04-10',
    inspectPlace: 'Cảng Cửa Sót',
    ownerInfo: 'Nguyễn Văn A - Thôn Hải Thành, Cẩm Nhượng',
    ownerNID: '123456789012',
    ownerPhone: '0901234567',
    captain: 'Trần Văn B',
    captainPassport: 'PA987654321',
    captainPhone: '0912345678',
    crewList: ['Lê Văn C', 'Phạm Văn D'],
    licenseNumber: 'GP0012023',
    fishType: ['Cá ngừ', 'Cá thu'],
    fishingGrounds: 'Quần đảo Hoàng Sa',
    seasons: 'Mùa hè',
    output: '12 tấn',
  },
  {
    key: '2',
    boatSymbol: 'VN002',
    boatType: 'Tàu khai thác ven bờ',
    regisDate: '2020-09-05',
    regisOffice: 'Chi cục Thủy sản Quảng Ngãi',
    occupation: ['Khai thác ven bờ'],
    harbourCode: 'QN002',
    inspectDate: '2022-10-20',
    inspectPlace: 'Cảng Sa Kỳ',
    ownerInfo: 'Phạm Thị D - Xã Bình Châu, Bình Sơn',
    ownerNID: '987654321098',
    ownerPhone: '0934567890',
    captain: 'Ngô Văn E',
    captainPassport: 'PA123456789',
    captainPhone: '0965432109',
    crewList: ['Bùi Văn F', 'Đỗ Văn G'],
    licenseNumber: 'GP0022022',
    fishType: ['Cá cơm', 'Tôm'],
    fishingGrounds: 'Vịnh Quảng Ngãi',
    seasons: 'Mùa xuân',
    output: '7 tấn',
  },
  {
    key: '3',
    boatSymbol: 'VN003',
    boatType: 'Tàu dịch vụ hậu cần nghề cá',
    regisDate: '2019-12-01',
    regisOffice: 'Chi cục Thủy sản Khánh Hòa',
    occupation: ['Hậu cần nghề cá'],
    harbourCode: 'KH003',
    inspectDate: '2023-02-28',
    inspectPlace: 'Cảng Đá Bạc',
    ownerInfo: 'Lê Văn H - TP Nha Trang',
    ownerNID: '456789012345',
    ownerPhone: '0971122334',
    captain: 'Vũ Văn I',
    captainPassport: 'PA192837465',
    captainPhone: '0987654321',
    crewList: ['Trịnh Văn J', 'Nguyễn Văn K'],
    licenseNumber: 'GP0032023',
    fishType: ['Cá nục', 'Cá cam'],
    fishingGrounds: 'Vịnh Nha Trang',
    seasons: 'Quanh năm',
    output: '20 tấn',
  },
];